version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "02:00"
      timezone: "Asia/Tokyo"
    groups:
      github-actions-minor-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    open-pull-requests-limit: 5
    commit-message:
      prefix: ci

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "02:15"
      timezone: "Asia/Tokyo"
    groups:
      go-modules-minor-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    open-pull-requests-limit: 5
    commit-message:
      prefix: deps
